### ISSUE TITLE
Change the Profile Image in profilepage.html

### ISSUE THREAD

**Issue by NtemKenyor** [KwickerHub/frontend#113]
**Describe the bug**
Change the profile image in profilepage.html

**File/Files you will work on**
profilepage.html

**Possible Lines of Code**
You should not add above the possible lines of code. (if given)

**Result or Final Looks**
You should have changed the default profile picture from the face of the woman to an anonymous general context profile image like the one below.

![146-1468479_my-profile-icon-blank-profile-picture-circle-hd](https://user-images.githubusercontent.com/60122117/198354615-b870a767-da71-4bd4-bfc3-c53cdec561ab.png)

**Comment by Sakshi-75** [comment]
Hi @NtemKenyor can I work on this?

**Comment by Mayureshkaulwar** [comment]
assign to me

**Comment by NtemKenyor** [comment]
Alright guys. You can go for it.

**Comment by sohanvichare7** [comment]
Hello @NtemKenyor , May I work on this ??

**Comment by VANSHAJB10** [comment]
please assign me this issue @NtemKenyor

**Comment by Sakshi-75** [comment]
Hi @NtemKenyor I raised a PR for this: #127 
Please review.
