### ISSUE TITLE
Enable user to change their Bio information

### ISSUE THREAD

**Issue by NtemKenyor** [KwickerHub/frontend#114]
**Describe the bug**
When a user double clicks(or if a user clicks on the edit icon you add) on his/her Bio information in profilepage.html, a textarea HTML TAG should appear with a save button below it. 

**File/Files you will work on**
profilepage.html

**Possible Lines of Code**
You should not add above the possible lines of code. (if given)

**Result or Final Looks**
Users should be able to change their bio from the default text to their desire.

**Comment by Sakshi-75** [comment]
Hi @NtemKenyor can I work on this?

**Comment by NtemKenyor** [comment]
@Sakshi-75, please do not always wait for me to assign the task to you even though that looks like standard procedure. Just start working and send a PR. I will review and ask for changes were possible or accept.  This is because I have a lot of duties here. Thank you for understanding.

**Comment by Gowrishankar04** [comment]
Hi @NtemKenyor ,

Raised PR for the issue. Please review and merge it.

Thanks
