### ISSUE TITLE
Fix Tables in aboutus.html

### ISSUE THREAD

**Issue by NtemKenyor** [KwickerHub/frontend#116]
**Describe the bug**
As much as HTML is simple, we still make mistakes. LOL. Please check the table in aboutus.html and fix it. 

**File/Files you will work on**
aboutus.html

**Possible Lines of Code**
You should not add above the possible lines of code. (if given)

**Result or Final Looks**
The Table opening tags and end tags should be alright. The HTML table should be fixed. Thank you.

**Comment by shrutilenka** [comment]
Hey @NtemKenyor  I am interested to work on this issue.Could you please assign this to me?

**Comment by salilbc** [comment]
Please review my PR for the fix

**Comment by NtemKenyor** [comment]
Well done guys.
