### ISSUE TITLE
Making Save, Auto Save and Load functionality for the UI Dashboard

### ISSUE THREAD

**Issue by NtemKenyor** [KwickerHub/frontend#117]
**Describe the bug**
The content in the UI DASHBOARD is not saved. However, we already have the functions and the required code to save and reload the design when needed. We need you to actualize a save, auto save and reload system to help the UI/UX section.

**File/Files you will work on**
ui_dashboard.html

**Possible Lines of Code**
You should not add above the possible lines of code. (if given)

**Result or Final Looks**
People should not loose their design work at all.

**Comment by ASANIYAN** [comment]
Would love to work on this. Can I get assigned?

**Comment by NtemKenyor** [comment]
I feel we have already solved this.
