### ISSUE TITLE
Shortcut Key for -- Delete 

### ISSUE THREAD

**Issue by NtemKenyor** [KwickerHub/frontend#123]
**Describe the bug**
With JavaScript, you can listen to user inputs. When even a user presses the delete key, we need you to call the remove element function.

**File/Files you will work on**
dashboard.html

**Possible Lines of Code**
You should not add above the possible lines of code. (if given)

**Result or Final Looks**
When a user presses "delete" on the key board, He should automatically remove the element from the development dashboard. 
HINT: Just call the function (removeSelected) - same function called when the user clicks on "Remove" from the top bar UNDER EDIT

**Comment by supsa-ak** [comment]
Hi, Please assign this issue to me. I am participating in Hacktoberfest.

**Comment by NtemKenyor** [comment]
@supsa-ak go on. And please in this project, Do not wait for issues to be assigned to you. Just start working and send us a PR straight on.

**Comment by NtemKenyor** [comment]
I am closing this because it is long overdue though some parts was solved and reopening it for some better trends.
