### ISSUE TITLE
Adding .gitignore

### ISSUE THREAD

**Issue by kull-boii** [KwickerHub/frontend#132]
## .gitignore is missing 

I can see some unnecessary files that have been committed because .gitignore wasn't created  

eg .DS_Store (DS_Store files are automatically created by Mac OS X Finder in browsed directories. These files contain information about system configuration. If you upload them along with other files, the files can be misused to obtain information about your computer. )

![image](https://user-images.githubusercontent.com/68529036/199331418-a036d74c-6a8d-464d-a889-90268bf83d27.png)

I will add .gitignore with all suitable files to be ignored while committing the code to github 

kindly assign me this.

**Comment by NtemKenyor** [comment]
@kull-boii done. Great observation👌
