### ISSUE TITLE
Top Menu Bar is displayed behind - Increase Z-Index

### ISSUE THREAD

**Issue by NtemKenyor** [KwickerHub/frontend#138]
**Describe the bug**
Top menu bar in dashboard.html is covered by the main content display

**To Reproduce**
1. Go to 'dashboard.html.'
2. Hover on 'The top menu Bar'
3. See error

**Expected behavior**
You will see that the menu bar sub-items are displayed but behind the main content. This menu bar items are suppose to come forward and rest on top of every other content.

**Additional context**
We need to increase the z-index of the top menu in dashboard.html to make it always on top.

**Comment by CodeDroid999** [comment]
increase the z-index of the top menu in dashboard.html to make it always on top.

**Comment by shyamtawli** [comment]
Hello @NtemKenyor can you please discribe or send some photos to understand the problem because as i see there no such issue in top menu.

**Comment by NtemKenyor** [comment]
thank you guys for your contributions
