### ISSUE TITLE
grammatic error

### ISSUE THREAD

**Issue by NtemKenyor** [KwickerHub/frontend#14]
I have noticed that some sentences do not make perfect sense. You can easily try to fix that.

**Comment by ParisaTork** [comment]
Happy to do this for you, if you'd like? Is it just the README.md that needs fixing?

**Comment by NtemKenyor** [comment]
Yeah.

The read.md needs fixing and I heard the is a way to design the read.md
file on GitHub to make it more colorful, attractive and informative.

Also, if you can spot out any misspelling or grammatic errors in other
corners of the project, please help in fixing it.

Thank you.

**Comment by ParisaTork** [comment]
Great - that's all been sorted :) Link to PR: https://github.com/KwickerHub/frontend/pull/16

**Comment by ParisaTork** [comment]
@NtemKenyor - if you're happy with this, you can merge it to master? https://github.com/KwickerHub/frontend/pull/16

**Comment by NtemKenyor** [comment]
Ok. I will go through everything. Thank you 💕

**Comment by NtemKenyor** [comment]
I have merged your contribution. thank you.

**Comment by NtemKenyor** [comment]
I will close this issue but i will be opening another to check for grammatical errors made by developers and proper documentation of the software.
