### ISSUE TITLE
Background Color Picker is not working - ui_dashboard

### ISSUE THREAD

**Issue by NtemKenyor** [KwickerHub/frontend#144]
**Describe the bug**
Background color selector is not working in ui_dashboard.html

**To Reproduce**
Steps to  ui_dashboard.html:
1. Go to home page, click on "Explore"
2. From dashboard.html, click on "pages" on the top menu
3. click on "UI DASHBOARD"
4. In the ui_dashboard.html file, try to add a box and change the background color.
5. You would observe that the change in color is not applied to the box.

**Expected behavior**
upon changing the color picker, the color of the box or shape in the development environment is suppose to change too.

**Additional context**
This feature is going to be added to the dashboard.html file and many more color selection areas.

**Comment by Himanshu-Vishwas** [comment]
Hi! I want to work on this bug.

**Comment by NtemKenyor** [comment]
hello @Himanshu-Vishwas I observed that you showed interest in solving a lot of issues but for sake of credibility and accountability, I would only assign two to you at the moment. Hopefully we can assign more to you in the future. Thank you and happy contributing.

**Comment by NtemKenyor** [comment]
I have solved it. Let's move on...
