### ISSUE TITLE
Add an Icon to dashboard.html

### ISSUE THREAD

**Issue by NtemKenyor** [KwickerHub/frontend#147]
**Describe the bug**
In the Dashboard.html file, we have the redirect icons by the left when you hover on "Pages" on the top bar. We would love to include another set of icons by the right. This new icons should be unique to that Page category and it should provide some  clue on where the user is heading to. For instance:

- Render Page(This describes a live view of your project): so an icon describing activity or live changes can be used.
- UI_Dashboard: An icon describing painting, drawing or creativity should be added to the right.
- Profile Page: An Icon describing a user or person should be added to the right.

**File/Files you will work on**
dashboard.html

**Possible Lines of Code**
You just need to adjust three sections of the code in dashboard.html file. All necessary imports have been already made.

**Result or Final Looks**
The redirect icon should be on the left and a new icon describing the new page should be added by the side. A user icon can be used by the right of the "Profile page".

**Comment by Himanshu-Vishwas** [comment]
Hi! I want to work on this issue.

**Comment by NtemKenyor** [comment]
@Himanshu-Vishwas please complete other issues assigned to you before this would be assigned to you.

**Comment by Himanshu-Vishwas** [comment]
I have completed another assigned issue. Please assign me this issue
