### ISSUE TITLE
Change Sub-menu Text

### ISSUE THREAD

**Issue by NtemKenyor** [KwickerHub/frontend#148]
**Describe the bug**
In the "ui_dashboard.html" page, we have the "UI Dashboard" sub-menu under Pages in the top Bar. Please change "UI Dashboard" to "Dashboard" and run the redirect to "dashboard.html" page.

**File/Files you will work on**
ui_dashbaord.html

**Possible Lines of Code**
Adjust already working content instead of adding more lines of code.

**Result or Final Looks**
We are suppose to redirect the user to the dashboard environment from the "UI dashboard" and not to the same page.

**Comment by Himanshu-Vishwas** [comment]
Hi! I want to work on this issue.

**Comment by NtemKenyor** [comment]
It has been assigned to you.

**Comment by Himanshu-Vishwas** [comment]
Please review the PR.
