### ISSUE TITLE
Listen to "delete" on keyboard to Delete elements

### ISSUE THREAD

**Issue by NtemKenyor** [KwickerHub/frontend#151]
### Describe the issue
With JavaScript, you can listen to user inputs. When even a user presses the delete key, we need you to call the remove element function.

### File/Files you will work on
dashboard.html ->(This file is linked to Dashboard JavaScript file and Dashboard CSS file. Therefore you can adjust them too if necessary)

### Possible Lines of Code
You should not add above the possible lines of code. (if given)

**Result or Final Looks**
When a user presses "delete" on the key board, He should automatically remove the element from the development dashboard.
_HINT: Just call the function (removeSelected) - same function called when the user clicks on "Remove" from the top bar UNDER EDIT_

**Comment by chiragjh7** [comment]
Hi, I want to work on this issue, can you assign it to me?

**Comment by NtemKenyor** [comment]
Done. Hoping to get a nice Pul Request from you. Happy Contributing 👍
