### ISSUE TITLE
Delete a Shape when "delete" is pressed on ui_dashboard.html

### ISSUE THREAD

**Issue by NtemKenyor** [KwickerHub/frontend#152]
**Describe the issue**
With JavaScript, you can listen to user inputs. When even a user presses the delete key, we need you to call the remove element(shape) function.

**File/Files you will work on**
ui_dashboard.html ->(This file is linked to UI-dashboard JavaScript file and UI-dashboard CSS file. Therefore you can adjust them too if necessary)

**Possible Lines of Code**
You should not add above the possible lines of code. (if given)

**Result or Final Looks**
When a user presses "delete" on the key board, He should automatically remove the element(shape) from the UI development dashboard.
_HINT: Just call the function (removeSelected) - same function called when the user clicks on "Remove" from the top bar UNDER EDIT_

**Comment by chiragjh7** [comment]
Hi, can you assign this issue to me?

**Comment by NtemKenyor** [comment]
@chiragjh7 We have assigned this issue to you. Happy Coding 😊
