### ISSUE TITLE
Info Button - Session of Buttons

### ISSUE THREAD

**Issue by NtemKenyor** [KwickerHub/frontend#164]
Inline with our "session of Buttons", We would be building different kinds of buttons..

Design a Button that looks like the button in this image...(Info_Button)

Create a file "Your_Button_Name.html" in the modules/buttons folder.

Use simple HTML and CSS to create the button.
For some additional info, You should read the instructions.txt file in "buttons" folder.
![Screenshot from 2023-04-14 12-57-06](https://user-images.githubusercontent.com/60122117/232105936-b16a438e-3612-4ab9-a9e6-b405310d64b6.png)

**Comment by royninja** [comment]
Hi, can you assign this to me?

**Comment by NtemKenyor** [comment]
yea. But just start something.
