### ISSUE TITLE
Primary Button - Let's make this button - Session of Buttons

### ISSUE THREAD

**Issue by NtemKenyor** [KwickerHub/frontend#165]
Inline with our "session of Buttons", We would be building different kinds of buttons..

Design a Button that looks like the button in this image...

Create a file "Your_Button_Name.html" in the modules/buttons folder.

Use simple HTML and CSS to create the button. You can use the interface development https://kwickerhub.com (This project) or you can code it.
For some additional info, You should read the instructions.txt file in "buttons" folder.
![Screenshot from 2023-04-14 12-56-35](https://user-images.githubusercontent.com/60122117/232107508-558ae6a8-a364-43b8-b75f-8cab492cdbd7.png)

**Comment by royninja** [comment]
Wanted to work on this. Can I get the issue assigned?

**Comment by NtemKenyor** [comment]
sure go on...
