### ISSUE TITLE
WhatsApp Button - Session of Buttons

### ISSUE THREAD

**Issue by NtemKenyor** [KwickerHub/frontend#177]
![Screenshot from 2023-04-14 12-55-23](https://user-images.githubusercontent.com/60122117/232230780-dc1c073e-fed6-4c74-bd5a-c91ebcaf4796.png)

Inline with our "session of Buttons", We would be building different kinds of buttons..

Design a Button that looks like the button in this image...

Create a file "WHATSAPP_BUTTON_BY_YOUR_NAME.html" in the modules/buttons folder.

Use simple HTML and CSS to create the button. You can use the interface development https://kwickerhub.com (This project) or you can write the lines of code yourself.

**Step by Step Guide.**

1. Fork this project(Use the 'fork' button in the top right corner) and Clone your Fork.
`git clone https://github.com/YOUR_USERNAME/frontend`

2. Open your code Editor and Create a file "WHATSAPP_BUTTON_BY_YOUR_NAME.html" in the "modules/buttons" folder of this project you just cloned. No need to create head, title and body tags, Just Add a div tag with some embedded style(i.e use the style tag) and the script tag where necessary.
  If you want to add an image resource, please add it in the folder "modules/buttons/images_and_icons"
3. Push your Code: You need to push your recent changes back to the cloud. Use the command below in the main directory of this Repository

`git push origin dev` 
or use a GUI tool to avoid mistakes or complexity. LOL.

4.  Make you Pull Request... if you do not know how to go about it, Just visit your fork on GitHub and you would see the button/suggestion to make a pull request to this project(the upstream)

Good-luck.
For some additional info, You should read the instructions.txt file in "buttons" folder.

**Comment by Hritik1503** [comment]
I am interested to work on this issue under Quine. So please assign me this issue to me.
