### ISSUE TITLE
Create "About us" Page

### ISSUE THREAD

**Issue by NtemKenyor** [KwickerHub/frontend#19]
We need someone to create an html page in the pages folder that will content a little description about us. The design can be made and the content will be added gradually.

**The Design**
The design should include our logo or a brand nice image of a hub and text content

**The content should include:**
What is the name of the Software?
What is the main aim of the Software?
Who invented the Software?
How many contributors have improved the software?

**Comment by Alve2000** [comment]
@NtemKenyor  Hey, I like to contribute to this project, Would appreciate it if you assign me.

**Comment by NtemKenyor** [comment]
I have assigned the task to you. You may also want to check out this introductory video: https://www.youtube.com/watch?v=p2z3frymoiU

**Comment by gaurav-iitb** [comment]
I also would like to contribute to it

**Comment by johnwinifred** [comment]
Hey, please I would also like to contribute to this

**Comment by gaurav-iitb** [comment]
@NtemKenyor  please review my pr

**Comment by NtemKenyor** [comment]
done.
