### ISSUE TITLE
Overlapblock

### ISSUE THREAD

**Issue by MaverickDe** [KwickerHub/frontend#234]
![Screenshot_20230509-001320](https://user-images.githubusercontent.com/100746581/236956859-00635da2-37ef-4e86-b27b-ebb686ebfe6e.jpg)

We will be starting the proceedings

Design a overlap block that look exactly like the above  image...

Create a file "OVERLAP_DESIGN.html" in the modules/overlapblock folder.

Use simple HTML and CSS and JAVASCRIPT to create the overlapblock. You can use the interface development https://kwickerhub.com (This project) or you can write the lines of code yourself.

**Step by Step Guide.**

Fork this project(Use the 'fork' button in the top right corner) and Clone your Fork.
git clone https://github.com/YOUR_USERNAME/frontend

Open your code Editor and Create a file "OVERLAP_DESIGN.html" in the "modules/overlapblock" folder of this project you just cloned. No need to create head, title and body tags, Just Add a div tag with some embedded style(i.e use the style tag) and the script tag where necessary.

If you want to add an image resource, please add it in the folder  ••
```"modules/overlapblock/images_and_icons"```
 We recommend you use an svg for your image/icon.

Push your Code: You need to push your recent changes back to the cloud. Use the command below in the main directory of this Repository

```git push origin dev```

or use a GUI tool to avoid mistakes or complexity. LOL.

Make you Pull Request... 
Good-luck.

**Comment by Shalini469717** [comment]
Can I work on this issue?

**Comment by MaverickDe** [comment]
Sure , fork the repo and carry on

**Comment by rahulchanumolu** [comment]
I will be working on this issue and will send the PR soon
