### ISSUE TITLE
Add an Icon in the view menu section

### ISSUE THREAD

**Issue by NtemKenyor** [KwickerHub/frontend#24]
Add an icon to the "View Page" in the view section in the menu of the dashbaord.html.

You can add two icons(to the left and right) but make sure to include a redirect icon because we will be redirecting the user to the "View Page" html file in a new tab.
This is a really simple task. Enjoy it.

**Comment by akashyadav24** [comment]
can you assigne me this task ?

**Comment by Nainish-Rai** [comment]
Hey, I want to contribute to this issue, Please assign me so that I can start working on it.

**Comment by samyaksand** [comment]
Hello, Im interested in working on this. Also, I have experience for contributing an icon to a different repository.
Link - https://github.com/feenotifier/apps

 Please assign me this issue.

**Comment by akashyadav24** [comment]
![image](https://user-images.githubusercontent.com/67678310/193406801-80d0d823-a00a-4f02-a4cc-0300f5b4e62f.png)
hey I added Icon in view page

**Comment by NtemKenyor** [comment]
that's a perfect example of what we're looking for. Nice one. I will assign
you 👍

**Comment by akashyadav24** [comment]
thank you

**Comment by Nainish-Rai** [comment]
Hey,
 anything else is required?

**Comment by NtemKenyor** [comment]
> Hey, anything else is required?

Yes the software is far from finish. Just keep checking for more issues the page.
