### ISSUE TITLE
Fix spelling errors in the home page

### ISSUE THREAD

**Issue by blindaks** [KwickerHub/frontend#278]
**Describe the bug**
There are some spelling errors and punctuation mistakes in the home page.
For example, 'develop' is written as 'develope' in the main heading.

![Screenshot (82)](https://github.com/KwickerHub/frontend/assets/128223364/3effb303-eb9d-4566-a47b-2ef63dcecd1e)
![Screenshot (83)](https://github.com/KwickerHub/frontend/assets/128223364/07a9942e-1546-4625-a442-70f0b6a9c571)

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by blindaks** [comment]
@MaverickDe Please assign this issue to me.

**Comment by MaverickDe** [comment]
> @MaverickDe Please assign this issue to me.

Go on

**Comment by blindaks** [comment]
@MaverickDe I have linked a pr for this issue. Kindly review this.
