### ISSUE TITLE
Create a Folder and Move Some Files

### ISSUE THREAD

**Issue by NtemKenyor** [KwickerHub/frontend#33]
move the following text files out of the pages folder
attributes.txt
css_style.txt
HTML elements.txt
test_parts.txt

You can create a folder in "assets". Call the new folder you created "addon"
Paste all the text files above into the "addon" folder

**Comment by neutr0ncodes** [comment]
Hey I would like to work on this issue can you please assign this issue to me?

**Comment by neutr0n420** [comment]
#37
