### ISSUE TITLE
Adding a block HTML Comment

### ISSUE THREAD

**Issue by NtemKenyor** [KwickerHub/frontend#40]
### Goal: 
The goal here is to add a comment inside the element(with the id "the_dev_dashboard") in the "dashboard .html". This comment will contain important information about the project. For instance; if that project needs bootstrap, If the project needs special fonts, the favicon, description, etc
This will also help the view_render page to from the back-end

Add the HTML comment below inside the HTML element before any other content

```
    <!-- <head>
        <title> #Particular Project Name</title>
        <script>
            //Plugin Start
            //##
            //Plugin End 
        </script>
    </head> -->
```

**One More Thing:**
A particular JavaScript function(called "add_element_2_dashboard" in "dashboard.js") changes the entire content of that particular element in line #110. We need your comment on  that element unchanged.

### Aim: 
We understand that the content of the body of the new page will be equivalent to the design/HTML elements in the development dashboard. However, Will have not developed a way to secret address the head section of the new Document. This secret comments will have a section where plugin and other tools can be imported for that particular project

**Comment by johnwinifred** [comment]
hey, I would love to work on this project

**Comment by NtemKenyor** [comment]
@johnwinifred  Done. I have assigned the task to you

**Comment by johnwinifred** [comment]
Quick Question;
Should I put up suggestions on how to make the dashboard page better as comments?

**Comment by NtemKenyor** [comment]
Thank you very much that will be really cool.

But do you want me to create a new issue for that? or would you like to push all the code once and for all? Sorry for the late response.

**Comment by johnwinifred** [comment]
You can create a new issue for that

**Comment by NtemKenyor** [comment]
ok I think we are done with this.
