### ISSUE TITLE
Call a Function

### ISSUE THREAD

**Issue by NtemKenyor** [KwickerHub/frontend#47]
We forgot to call the function that displays the contribution to elements. So when the "contribution" menu in "dashboard.html" is clicked, the entire pop-up is still until you click another tab. 

You task is to call the function that will display the contribution form for elements.

**Comment by OgunmisiM** [comment]
can this be assigned to me ?
Have the function been created?

**Comment by NtemKenyor** [comment]
alright 👍 I have assigned this to you

**Comment by OgunmisiM** [comment]
i went through the website now, you mean the contribute link, right.

I clicked on it and the pop up showed, do you want it to display only when it is clicked

**Comment by NtemKenyor** [comment]
For further explanation, We have two functions.

The first function is activated when you click on the "contribute"
menu/link as you have earlier said. The aim of the first function is to
display the contribution page containing(Element contribution, Style,
Attribute and module contribution). That works just fine.

However, When the contribution pop-up appears it only displays headers and
no bodily content in the iframe. The reason is because the function that
handles that was not called. To display the bodily content, You may then
need to click the headers again.

Your Job is to search for both functions. Your contribution will only be in
the function that is called when user clicks on "contribute". append a call
on the end of this function to provide bodily content when the users click
"contribute".
