### ISSUE TITLE
Add a Circle to the "ui_dashboard.html"

### ISSUE THREAD

**Issue by NtemKenyor** [KwickerHub/frontend#48]
When the square-like-icon on the bottom tab of the page is clicked, we see clearly that a square is added to UI dashboard environment. Your goal is to activate the circle icon on the bottom of the page. So! Add a circle to the UI_development environment....

**Comment by ProtyayMnd50** [comment]
Can you assign me this @NtemKenyor  pls?

**Comment by NtemKenyor** [comment]
Thanks. that will be great 😊

**Comment by NtemKenyor** [comment]
Hello guys. I will be closing this issue because @aadi58002 solved it.

**Comment by NtemKenyor** [comment]
I will like you guys @ProtyayMnd50  and  @aadi58002 to check out the new issue I raised similar to this one. Add text and other shapes #93 #92
