### ISSUE TITLE
Add drop down options for users to select from

### ISSUE THREAD

**Issue by NtemKenyor** [KwickerHub/frontend#55]
Some attributes and styles require some unique values and it will be better to use a drop down or a select box in the input filed.

add dropdown options in the form box so users can select options provided instead of typing
eg(display — block, inline, flex, grid options).

**Comment by NtemKenyor** [comment]
This issues requires you to work on the dashboard.html page

**Comment by tab21** [comment]
Hi 
Can this issue be assigned to me ?

**Comment by NtemKenyor** [comment]
ok. Done

**Comment by NtemKenyor** [comment]
Further Explanation

At the moment, all the attributes and styles in the dashboard.html file all use input tags. This is appropriate for styles and attributes that we do not know their possible values but for some cases where a set of values are required, it is proper to use a drop down box or a select/option box

For instance the CSS property "float" can be set to "right", "left", "none", etc
also the CSS property "display" can be set to "block", "inline", "inline-block", "table-inline", etc

In this cases, we do not want an input box, we need a select box containing the required/possible values.

**Comment by tab21** [comment]
Okay thank you 
I will get back after trying

**Comment by johnwinifred** [comment]
Can this issue also be assigned to me

**Comment by NtemKenyor** [comment]
That's ok

**Comment by NtemKenyor** [comment]
Yes. Sure.

**Comment by NtemKenyor** [comment]
This is resolved. Thank you all.

Check out the new issues about making a similar drop down for font families
