### ISSUE TITLE
Add a Color Picker for every color related attribute or style

### ISSUE THREAD

**Issue by NtemKenyor** [KwickerHub/frontend#56]
Adding a color picker for the color attributes and styles in case the user is unsure of the Hex or rgba code.

**Comment by rajnish254** [comment]
Assign me that issue
Thanks

**Comment by Ezekiel8807** [comment]
Where exactly am I to add the color picker

**Comment by Ezekiel8807** [comment]
You can assign this to me I will love to work on it

**Comment by NtemKenyor** [comment]
Hello @Ezekiel8807, @rajnish254 
I am going to close this issue because it is one of the simplest issues at the moment to solve. A solution was provided in the ui_dashboard.html file. You can check it out and use it to contribute to the dashboard.html file

Your contribution is in the dashboard.html file
