### ISSUE TITLE
Add little Style to elements with the class= "each_item"

### ISSUE THREAD

**Issue by NtemKenyor** [KwickerHub/frontend#57]
Text with class ” each_item”
*For long text behind the box; set text_overflow to ellipses and on hover full text is displayed to user.
The_bottom_bar

**Comment by Sakshi-75** [comment]
Hi @NtemKenyor ,
I would like to work on this. Can you assign it to me?

**Comment by NtemKenyor** [comment]
@Sakshi-75 at the time of seeing this message, I have already received a pull request from @kull-boii 

Please, @Sakshi-75 I will be on the look to assign further issues to you. Thank you.

**Comment by NtemKenyor** [comment]
Anyways, Thank you @kull-boii
