### ISSUE TITLE
Social Media Manager

### ISSUE THREAD

**Issue by NtemKenyor** [KwickerHub/frontend#60]
We need a Contributor that will love to post updates about KwickerHub on Facebook,Twitter and even Instagram

Be rest assured that you will be come a maintainer and part of our core team.

**Comment by johnwinifred** [comment]
I would really love to work on this 
I can create infographics, banners and short videos on the project.

**Comment by NtemKenyor** [comment]
That will be awesome. how many short videos are we looking at?

If given details to our Twitter, Instagram, Facebook Page can you manage it? Do you have some knowledge about Facebook advertising?

**Comment by johnwinifred** [comment]
Two videos on Instagram and Twitter
Then infographics and banners on Facebook.
Hmmm about Facebook advertising I will look that up

**Comment by johnwinifred** [comment]
About managing the pages I can absolutely do that

**Comment by NtemKenyor** [comment]
Hello @johnwinifred We can talk more on a messaging platform like WhatsApp, +2349097441316. i will be closing this issue.

**Comment by johnwinifred** [comment]
Ok
