### ISSUE TITLE
Logo Url not working

### ISSUE THREAD

**Issue by kull-boii** [KwickerHub/frontend#68]
When the logo is clicked
![image](https://user-images.githubusercontent.com/68529036/194827766-597691e5-6291-4bf1-8c78-31fd9896a59d.png)

it results a 404 error

![image](https://user-images.githubusercontent.com/68529036/194827812-2a679a2d-ec5a-45fd-be14-7cb163de7b19.png)

**Comment by NtemKenyor** [comment]
I like the fact that you created the issue and didn't wait for me. Truth be told, I did not even observe that. Thank you. More please 😊
