### ISSUE TITLE
Fix landing page overflowing in mobile view

### ISSUE THREAD

**Issue by sarthakastic** [KwickerHub/frontend#81]
The landing page is overflowing in mobile view

<img width="1710" alt="Screenshot 2022-10-13 at 1 35 23 AM" src="https://user-images.githubusercontent.com/72138026/195437428-9de3ae9c-4b29-4425-b506-9cf27e9a6a35.png">

**Comment by NtemKenyor** [comment]
ok. Thank you for noticing this. Would you be handling this? or would you like me to assign this issue to another person?

**Comment by sarthakastic** [comment]
Yes pls assign it to me under hacktoberfest label

**Comment by Ezekiel8807** [comment]
I can do that, if it's still available

**Comment by Ezekiel8807** [comment]
![overflow](https://user-images.githubusercontent.com/57665815/195952151-83294eee-ceec-4499-941d-238167b65d1f.PNG)
![overflow2](https://user-images.githubusercontent.com/57665815/195952165-286ef295-0304-4108-8772-da2a5f5e745f.PNG)

I will really love to fix this issue if its still open

**Comment by NtemKenyor** [comment]
I have not received a pull request for now.
