### ISSUE TITLE
Add Text/Fonts in the UI_dashboard

### ISSUE THREAD

**Issue by NtemKenyor** [KwickerHub/frontend#92]
**Describe the bug**
Just like people can add squares and circles, We want out users to be able to add text content. When the User clicks the font/text icon on that bottom bar, A default text should always be adding on the development environment.

**File/Files you will work on**
ui_dashboard.html

**Possible Lines of Code**
You should not add above the possible lines of code. (if given) 

**Result or Final Looks**
We except the users to able to add some text.

**Comment by aadi58002** [comment]
Can you assign it to me ?

**Comment by gitamandeep** [comment]
@NtemKenyor please assign this task to me.
