### ISSUE TITLE
Add Image in UI_dashboard

### ISSUE THREAD

**Issue by NtemKenyor** [KwickerHub/frontend#93]
**Describe the bug**
Just like adding a square and circle, We need our users to be able to add images.
You will need to add an image or gallery icon on the bottom bar
When users click the added icon, a default image should always be added on screen

**File/Files you will work on**
ui_dashboard.html

**Possible Lines of Code**
You should not add above the possible lines of code. (if given)

**Result or Final Looks**
Users should be able to add images to a default image to the ui_dashboard

**Comment by aadi58002** [comment]
Can you assign it to me?

**Comment by NtemKenyor** [comment]
Done @aadi58002
