### ISSUE TITLE
Save Project Automatically

### ISSUE THREAD

**Issue by NtemKenyor** [KwickerHub/frontend#94]
**Describe the bug**
We do not want people to loss their work or projects, So we intend to automatically save their projects.
Algo 1:
U can use a time interval to always call the save function

Algo 2 & Better
We only want to save content when the user adds content or when the user is active. So to achieve this, We intend to call the Save function when a new item is added to the development dashboard or after 10 active clicks

**File/Files you will work on**
dashboard.html if your code looks code, You can make another pull request for the ui_dashboard page

**Possible Lines of Code**
You should not add above the possible lines of code. (if given)

**Result or Final Looks**
Projects will be saved automatically.

**Comment by aadi58002** [comment]
Can you assign it to me?

**Comment by NtemKenyor** [comment]
I was able to work on this. We can now save content automatically. And the content is recovered when ever the page is loaded. Though I plan on improving the code better.
